FROM maven:3.5.4-jdk-8-slim

RUN apt-get update && apt-get install -y build-essential

WORKDIR /app
ADD  . .
RUN mvn install -DskipTests=true

VOLUME /data/task-data
WORKDIR /data/task-data

EXPOSE 9091
CMD ["/bin/bash", "-c", "cp -R /app/. /data/task-data/ && /agent-download-directory/agent"]
